### ISSUE TITLE
Doesn't this library support custom headers?

### ISSUE THREAD

**Issue by gunhak01** [akalend/amqpcpp#102]
I got as far as adding headers through exchange->setHeader(), but the built-in headers (Delivery-mode, Content-type) are sent properly, but the custom header I created (Filename) is not sent.

**Comment by rasecoiac03** [comment]
This is made with https://github.com/akalend/amqpcpp/blob/f6466a45556d0589583ba43f63eb11c8f356e82c/include/AMQPcpp.h#L266 but this can be refactored as well for sure (rename it for `custom` instead of `special`).
