### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by Sean-Brown** [akalend/amqpcpp#37]
I found that there were some memory leaks associated with creating AMQPExchange and AMQPQueue objects using AMQP::createExchange()/createQueue(). The leak has to do with the way the classes are declared in amqpcpp.h:

When createExchange() or createQueue() is called, the object that's created is cast to AMQPBase\* using a reinterpret_cast and put on the AMQPConenction's "channels" vector. Since the destructor for AMQPBase is not virtual, the destructors for AMQPExchange and AMQPQueue are not called, thus all the memory that was allocated for them is not released.

The fix:
- Change AMQPBase's destructor to be virtual
- Change AMQPQueue's destructor to be virtual (not necessary, but good practice)
- Create a virtual destructor for AMQPExchange (again, not necessary, but good practice)
- Change the "reinterpret_cast" to "dynamic_cast" in AMQP::createExchange()/createQueue()

**Comment by SeanEClarke** [comment]
Checked the list of fixes and all these have been applied.

Suggest this is closed.
