### ISSUE TITLE
addEvent callbacks only take a C style function pointers and prevent/hinder a more OO approach

### ISSUE THREAD

**Issue by SeanEClarke** [akalend/amqpcpp#54]
Currently the event callbacks are all assumed to be C style function pointers.

What is the appetite for changing this to be something like std::function<int(AMQPMessage*)> and so allow pointers to C++ member functions etc or a lambda. This will allow a more OO approach and facilitate some established design patterns (MessageListener etc. from Java) to be employed or enable access to member variables for the message processing etc..

**Comment by SeanEClarke** [comment]
I've written a patch for this if you are interest

**Comment by SeanEClarke** [comment]
and pull request raised

**Comment by akalend** [comment]
merged
