### ISSUE TITLE
Can anyone explain what is the structure of this string "123123:akalend@localhost:5673/private" used to create socket?

### ISSUE THREAD

**Issue by jadhavshital** [akalend/amqpcpp#80]
Explain how `123123:akalend@localhost:5672/private` string forms?

```
Username : admin
password : admin
port : 5672
host : localhost
Cluster name : rabbit@mindconnect
```
Which parameters are required to form the above string?

But what is `123123` in the above string?

Thanks in advance.

**Comment by akalend** [comment]
I don't work with cluster? You connection string for localhost is:
 admin:admin@localhost:5672/private

**Comment by jadhavshital** [comment]
Thank you for reply. I got my answer.

**Comment by jadhavshital** [comment]
Thank you for reply. I got my answer.
